services:
  - type: web
    name: yanswap-license-server
    env: python
    plan: free
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
